name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets :
    - assets/clock.png
    - assets/Ellipse 3.png
    - assets/undraw_back_to_school_inwc 1.png
    - assets/undraw_done_checking_re_6vyx 1.png
